name: Nexlog CI

on:
  push:
    branches: 
      - "master"  # Test on push to master
  pull_request:
    branches: 
      - "master"  # Test on PR to master
      - "develop" # Test on PRs to develop (e.g., feature/* -> develop)
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        zig-version: ['0.13.0', 'master']

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: ${{ matrix.zig-version }}

    - name: Zig version
      run: zig version

    - name: Build
      run: zig build

    - name: Run tests
      run: zig build test

    - name: Run examples
      if: success()
      run: zig build examples

    - name: Cache zig dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/zig
          zig-cache
        key: ${{ runner.os }}-zig-${{ matrix.zig-version }}-${{ hashFiles('**/build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-${{ matrix.zig-version }}-
